# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        company:
            dynamic: false
            properties:
                id: { type: integer }
                title: { type: text }
                address: { type: text }
                city: { type: text }
                zipcode: { type: text }
                category: { type: text }
                description: { type: text }
            persistence:
                driver: orm
                model: App\Entity\Company

