# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        company:
            properties:
                title: ~
                address: ~
                city: ~
                zipcode: ~
                category: ~
                description: ~
            persistence:
                driver: orm
                model: App\Entity\Company

