services:

  #PHP Service
  app:
    image: php:8.1.18-fpm-alpine
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arcatest
    env_file:
      - .env
    restart: unless-stopped
    tty: true
    user: root
    volumes:
      - ./:/var/www
      - ./docker-compose/entrypoint.sh:/etc/entrypoint.sh
      - ./docker-compose/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    working_dir: /var/www
    networks:
      - arcatest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      mariadb:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  #Nginx Service
  webserver:
    image: nginx:stable-alpine3.17
    container_name: arcatest-nginx
    env_file:
      - .env
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - arcatest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      mariadb:
        condition: service_healthy
      app:
        condition: service_started

  #MySQL Service
  mariadb:
    image: mariadb:10.9.5
    container_name: arcatest-mariadb
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: '${DB_PASS}'
      MARIADB_ROOT_HOST: "%"
      MARIADB_DATABASE: '${DB_NAME}'
      MARIADB_USER: '${DB_USER}'
      MARIADB_PASSWORD: '${DB_PASS}'
    volumes:
      - mariadb:/var/lib/mysql
      - ./docker-compose/mariadb:/docker-entrypoint-initdb.d
    networks:
      - arcatest
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASS}" ]
      retries: 20
      interval: 5s
      timeout: 5s

  #Elasticsearch Service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: arcatest-elasticsearch
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - http.cors.enabled=true
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - arcatest
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      retries: 20
      interval: 5s
      timeout: 5s
    depends_on:
      mariadb:
        condition: service_healthy
  

#Docker Networks
networks:
  arcatest:
    driver: bridge
volumes:
  mariadb:
    driver: local
  elasticsearch:
    driver: local