parameters:
    database_host: host.docker.internal
    database_port: 3306
    database_name: arca
    database_user: arca
    database_password: arca

    secret: ThisTokenIsNotSoSecretChangeIt

    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: ~
    mailer_password: ~